//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPOS.WsRedemption {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.payback.net/lmsglobal/ws/v1/extint", ConfigurationName="WsRedemption.ExtintPortType")]
    public interface ExtintPortType {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación GetAliasDashboard no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="GetAliasDashboard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessageResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AuthorisedRequest))]
        WebPOS.WsRedemption.GetAliasDashboardResponse1 GetAliasDashboard(WebPOS.WsRedemption.GetAliasDashboardRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetAliasDashboard", ReplyAction="*")]
        System.Threading.Tasks.Task<WebPOS.WsRedemption.GetAliasDashboardResponse1> GetAliasDashboardAsync(WebPOS.WsRedemption.GetAliasDashboardRequest1 request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación ProcessDirectRedemptionEvent no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="ProcessDirectRedemptionEvent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessageResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AuthorisedRequest))]
        WebPOS.WsRedemption.ProcessDirectRedemptionEventResponse1 ProcessDirectRedemptionEvent(WebPOS.WsRedemption.ProcessDirectRedemptionEventRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="ProcessDirectRedemptionEvent", ReplyAction="*")]
        System.Threading.Tasks.Task<WebPOS.WsRedemption.ProcessDirectRedemptionEventResponse1> ProcessDirectRedemptionEventAsync(WebPOS.WsRedemption.ProcessDirectRedemptionEventRequest1 request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación RefundDirectRedemptionEvent no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="RefundDirectRedemptionEvent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessageResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AuthorisedRequest))]
        WebPOS.WsRedemption.RefundDirectRedemptionEventResponse1 RefundDirectRedemptionEvent(WebPOS.WsRedemption.RefundDirectRedemptionEventRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="RefundDirectRedemptionEvent", ReplyAction="*")]
        System.Threading.Tasks.Task<WebPOS.WsRedemption.RefundDirectRedemptionEventResponse1> RefundDirectRedemptionEventAsync(WebPOS.WsRedemption.RefundDirectRedemptionEventRequest1 request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación ReverseRedemptionEvent no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="ReverseRedemptionEvent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessageResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AuthorisedRequest))]
        WebPOS.WsRedemption.ReverseRedemptionEventResponse1 ReverseRedemptionEvent(WebPOS.WsRedemption.ReverseRedemptionEventRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="ReverseRedemptionEvent", ReplyAction="*")]
        System.Threading.Tasks.Task<WebPOS.WsRedemption.ReverseRedemptionEventResponse1> ReverseRedemptionEventAsync(WebPOS.WsRedemption.ReverseRedemptionEventRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.payback.net/lmsglobal/ws/v1/extint/types")]
    public partial class GetAliasDashboardRequest : AuthorisedRequest {
        
        private MemberIdentificationType identificationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MemberIdentificationType Identification {
            get {
                return this.identificationField;
            }
            set {
                this.identificationField = value;
                this.RaisePropertyChanged("Identification");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.payback.net/lmsglobal/xsd/v1/types")]
    public partial class MemberIdentificationType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string aliasField;
        
        private PrincipalVariantType aliasTypeField;
        
        private bool aliasTypeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
                this.RaisePropertyChanged("Alias");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public PrincipalVariantType AliasType {
            get {
                return this.aliasTypeField;
            }
            set {
                this.aliasTypeField = value;
                this.RaisePropertyChanged("AliasType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AliasTypeSpecified {
            get {
                return this.aliasTypeFieldSpecified;
            }
            set {
                this.aliasTypeFieldSpecified = value;
                this.RaisePropertyChanged("AliasTypeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.payback.net/lmsglobal/xsd/v1/types")]
    public enum PrincipalVariantType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.payback.net/lmsglobal/xsd/v1/types")]
    public partial class MemberAliasIdentificationType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MemberIdentificationType identificationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MemberIdentificationType Identification {
            get {
                return this.identificationField;
            }
            set {
                this.identificationField = value;
                this.RaisePropertyChanged("Identification");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.payback.net/lmsglobal/xsd/v1/types")]
    public partial class ReferencePurchaseDetailsType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LegalUnitType rewardableLegalValueField;
        
        private string receiptNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public LegalUnitType RewardableLegalValue {
            get {
                return this.rewardableLegalValueField;
            }
            set {
                this.rewardableLegalValueField = value;
                this.RaisePropertyChanged("RewardableLegalValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ReceiptNumber {
            get {
                return this.receiptNumberField;
            }
            set {
                this.receiptNumberField = value;
                this.RaisePropertyChanged("ReceiptNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.payback.net/lmsglobal/xsd/v1/types")]
    public partial class LegalUnitType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal legalAmountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal LegalAmount {
            get {
                return this.legalAmountField;
            }
            set {
                this.legalAmountField = value;
                this.RaisePropertyChanged("LegalAmount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.payback.net/lmsglobal/xsd/v1/types")]
    public partial class TransactionDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int transactionTypeField;
        
        private string marketingCodeField;
        
        private LoyaltyUnitType totalPointsField;
        
        private System.DateTime pointsBlockedUntilField;
        
        private bool pointsBlockedUntilFieldSpecified;
        
        private double vATRateField;
        
        private bool vATRateFieldSpecified;
        
        private ReferencePurchaseDetailsType[] referencePurchaseDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int TransactionType {
            get {
                return this.transactionTypeField;
            }
            set {
                this.transactionTypeField = value;
                this.RaisePropertyChanged("TransactionType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MarketingCode {
            get {
                return this.marketingCodeField;
            }
            set {
                this.marketingCodeField = value;
                this.RaisePropertyChanged("MarketingCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public LoyaltyUnitType TotalPoints {
            get {
                return this.totalPointsField;
            }
            set {
                this.totalPointsField = value;
                this.RaisePropertyChanged("TotalPoints");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime PointsBlockedUntil {
            get {
                return this.pointsBlockedUntilField;
            }
            set {
                this.pointsBlockedUntilField = value;
                this.RaisePropertyChanged("PointsBlockedUntil");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PointsBlockedUntilSpecified {
            get {
                return this.pointsBlockedUntilFieldSpecified;
            }
            set {
                this.pointsBlockedUntilFieldSpecified = value;
                this.RaisePropertyChanged("PointsBlockedUntilSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public double VATRate {
            get {
                return this.vATRateField;
            }
            set {
                this.vATRateField = value;
                this.RaisePropertyChanged("VATRate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VATRateSpecified {
            get {
                return this.vATRateFieldSpecified;
            }
            set {
                this.vATRateFieldSpecified = value;
                this.RaisePropertyChanged("VATRateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ReferencePurchaseDetails", Order=5)]
        public ReferencePurchaseDetailsType[] ReferencePurchaseDetails {
            get {
                return this.referencePurchaseDetailsField;
            }
            set {
                this.referencePurchaseDetailsField = value;
                this.RaisePropertyChanged("ReferencePurchaseDetails");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.payback.net/lmsglobal/xsd/v1/types")]
    public partial class LoyaltyUnitType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal loyaltyAmountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal LoyaltyAmount {
            get {
                return this.loyaltyAmountField;
            }
            set {
                this.loyaltyAmountField = value;
                this.RaisePropertyChanged("LoyaltyAmount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.payback.net/lmsglobal/xsd/v1/types")]
    public partial class DirectRedemptionItemDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LoyaltyUnitType redemptionLoyaltyValueField;
        
        private LegalUnitType redemptionLegalValueField;
        
        private LegalUnitType totalPurchaseValueField;
        
        private LegalUnitType totalVatValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public LoyaltyUnitType RedemptionLoyaltyValue {
            get {
                return this.redemptionLoyaltyValueField;
            }
            set {
                this.redemptionLoyaltyValueField = value;
                this.RaisePropertyChanged("RedemptionLoyaltyValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public LegalUnitType RedemptionLegalValue {
            get {
                return this.redemptionLegalValueField;
            }
            set {
                this.redemptionLegalValueField = value;
                this.RaisePropertyChanged("RedemptionLegalValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public LegalUnitType TotalPurchaseValue {
            get {
                return this.totalPurchaseValueField;
            }
            set {
                this.totalPurchaseValueField = value;
                this.RaisePropertyChanged("TotalPurchaseValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public LegalUnitType TotalVatValue {
            get {
                return this.totalVatValueField;
            }
            set {
                this.totalVatValueField = value;
                this.RaisePropertyChanged("TotalVatValue");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.payback.net/lmsglobal/xsd/v1/types")]
    public partial class PartnerContextType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string partnerShortNameField;
        
        private string businessUnitShortNameField;
        
        private string branchShortNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PartnerShortName {
            get {
                return this.partnerShortNameField;
            }
            set {
                this.partnerShortNameField = value;
                this.RaisePropertyChanged("PartnerShortName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string BusinessUnitShortName {
            get {
                return this.businessUnitShortNameField;
            }
            set {
                this.businessUnitShortNameField = value;
                this.RaisePropertyChanged("BusinessUnitShortName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string BranchShortName {
            get {
                return this.branchShortNameField;
            }
            set {
                this.branchShortNameField = value;
                this.RaisePropertyChanged("BranchShortName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.payback.net/lmsglobal/xsd/v1/types")]
    public partial class RedemptionEventType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PartnerContextType partnerField;
        
        private System.DateTime effectiveTimeField;
        
        private string receiptNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PartnerContextType Partner {
            get {
                return this.partnerField;
            }
            set {
                this.partnerField = value;
                this.RaisePropertyChanged("Partner");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime EffectiveTime {
            get {
                return this.effectiveTimeField;
            }
            set {
                this.effectiveTimeField = value;
                this.RaisePropertyChanged("EffectiveTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ReceiptNumber {
            get {
                return this.receiptNumberField;
            }
            set {
                this.receiptNumberField = value;
                this.RaisePropertyChanged("ReceiptNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.payback.net/lmsglobal/xsd/v1/types")]
    public partial class MemberSecurityType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PrincipalSecretType secretTypeField;
        
        private string secretField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PrincipalSecretType SecretType {
            get {
                return this.secretTypeField;
            }
            set {
                this.secretTypeField = value;
                this.RaisePropertyChanged("SecretType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Secret {
            get {
                return this.secretField;
            }
            set {
                this.secretField = value;
                this.RaisePropertyChanged("Secret");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.payback.net/lmsglobal/xsd/v1/types")]
    public enum PrincipalSecretType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.payback.net/lmsglobal/xsd/v1/types")]
    public partial class MemberAliasAuthenticationType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MemberIdentificationType identificationField;
        
        private MemberSecurityType securityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MemberIdentificationType Identification {
            get {
                return this.identificationField;
            }
            set {
                this.identificationField = value;
                this.RaisePropertyChanged("Identification");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public MemberSecurityType Security {
            get {
                return this.securityField;
            }
            set {
                this.securityField = value;
                this.RaisePropertyChanged("Security");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.payback.net/lmsglobal/xsd/v1/types")]
    public partial class RedemptionOptionDisplayType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int redemptionTransactionTypeField;
        
        private RedemptionOptionStatusType redemptionOptionStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int RedemptionTransactionType {
            get {
                return this.redemptionTransactionTypeField;
            }
            set {
                this.redemptionTransactionTypeField = value;
                this.RaisePropertyChanged("RedemptionTransactionType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public RedemptionOptionStatusType RedemptionOptionStatus {
            get {
                return this.redemptionOptionStatusField;
            }
            set {
                this.redemptionOptionStatusField = value;
                this.RaisePropertyChanged("RedemptionOptionStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.payback.net/lmsglobal/xsd/v1/types")]
    public enum RedemptionOptionStatusType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.payback.net/lmsglobal/xsd/v1/types")]
    public partial class ExpiryStatisticsType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal expiredPointsAmountField;
        
        private System.DateTime expiredSinceDateField;
        
        private bool expiredSinceDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal ExpiredPointsAmount {
            get {
                return this.expiredPointsAmountField;
            }
            set {
                this.expiredPointsAmountField = value;
                this.RaisePropertyChanged("ExpiredPointsAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime ExpiredSinceDate {
            get {
                return this.expiredSinceDateField;
            }
            set {
                this.expiredSinceDateField = value;
                this.RaisePropertyChanged("ExpiredSinceDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpiredSinceDateSpecified {
            get {
                return this.expiredSinceDateFieldSpecified;
            }
            set {
                this.expiredSinceDateFieldSpecified = value;
                this.RaisePropertyChanged("ExpiredSinceDateSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.payback.net/lmsglobal/xsd/v1/types")]
    public partial class ExpiryAnnouncementType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal pointsToExpireAmountField;
        
        private System.DateTime nextExpiryDateField;
        
        private bool nextExpiryDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal PointsToExpireAmount {
            get {
                return this.pointsToExpireAmountField;
            }
            set {
                this.pointsToExpireAmountField = value;
                this.RaisePropertyChanged("PointsToExpireAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime NextExpiryDate {
            get {
                return this.nextExpiryDateField;
            }
            set {
                this.nextExpiryDateField = value;
                this.RaisePropertyChanged("NextExpiryDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NextExpiryDateSpecified {
            get {
                return this.nextExpiryDateFieldSpecified;
            }
            set {
                this.nextExpiryDateFieldSpecified = value;
                this.RaisePropertyChanged("NextExpiryDateSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.payback.net/lmsglobal/xsd/v1/types")]
    public partial class AccountBalanceDetailType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal totalPointsAmountField;
        
        private decimal availablePointsAmountField;
        
        private decimal blockedPointsAmountField;
        
        private ExpiryAnnouncementType expiryAnnouncementField;
        
        private ExpiryStatisticsType expiryStatisticsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal TotalPointsAmount {
            get {
                return this.totalPointsAmountField;
            }
            set {
                this.totalPointsAmountField = value;
                this.RaisePropertyChanged("TotalPointsAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal AvailablePointsAmount {
            get {
                return this.availablePointsAmountField;
            }
            set {
                this.availablePointsAmountField = value;
                this.RaisePropertyChanged("AvailablePointsAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal BlockedPointsAmount {
            get {
                return this.blockedPointsAmountField;
            }
            set {
                this.blockedPointsAmountField = value;
                this.RaisePropertyChanged("BlockedPointsAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public ExpiryAnnouncementType ExpiryAnnouncement {
            get {
                return this.expiryAnnouncementField;
            }
            set {
                this.expiryAnnouncementField = value;
                this.RaisePropertyChanged("ExpiryAnnouncement");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public ExpiryStatisticsType ExpiryStatistics {
            get {
                return this.expiryStatisticsField;
            }
            set {
                this.expiryStatisticsField = value;
                this.RaisePropertyChanged("ExpiryStatistics");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.payback.net/lmsglobal/xsd/v1/types")]
    public partial class FaultDescriptorType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string messageField;
        
        private string requestIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string RequestID {
            get {
                return this.requestIDField;
            }
            set {
                this.requestIDField = value;
                this.RaisePropertyChanged("RequestID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.payback.net/lmsglobal/xsd/v1/types")]
    public partial class MessageResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FaultDescriptorType faultMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public FaultDescriptorType FaultMessage {
            get {
                return this.faultMessageField;
            }
            set {
                this.faultMessageField = value;
                this.RaisePropertyChanged("FaultMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.payback.net/lmsglobal/xsd/v1/types")]
    public partial class ConsumerAuthenticationType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string principalField;
        
        private string credentialField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Principal {
            get {
                return this.principalField;
            }
            set {
                this.principalField = value;
                this.RaisePropertyChanged("Principal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Credential {
            get {
                return this.credentialField;
            }
            set {
                this.credentialField = value;
                this.RaisePropertyChanged("Credential");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.payback.net/lmsglobal/xsd/v1/types")]
    public partial class ConsumerIdentificationType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ConsumerAuthenticationType consumerAuthenticationField;
        
        private string deviceIDField;
        
        private VersionType versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ConsumerAuthenticationType ConsumerAuthentication {
            get {
                return this.consumerAuthenticationField;
            }
            set {
                this.consumerAuthenticationField = value;
                this.RaisePropertyChanged("ConsumerAuthentication");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DeviceID {
            get {
                return this.deviceIDField;
            }
            set {
                this.deviceIDField = value;
                this.RaisePropertyChanged("DeviceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public VersionType Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.payback.net/lmsglobal/xsd/v1/types")]
    public enum VersionType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.payback.net/lmsglobal/xsd/v1/types")]
    public partial class AuthorisedRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ConsumerIdentificationType consumerIdentificationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ConsumerIdentificationType ConsumerIdentification {
            get {
                return this.consumerIdentificationField;
            }
            set {
                this.consumerIdentificationField = value;
                this.RaisePropertyChanged("ConsumerIdentification");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.payback.net/lmsglobal/ws/v1/extint/types")]
    public partial class GetAliasDashboardResponse : MessageResponse {
        
        private AccountBalanceDetailType pointsStatementListItemField;
        
        private EnrollmentStatusType enrollmentStatusField;
        
        private RedemptionOptionDisplayType[] redemptionOptionListItemField;
        
        private string membershipIdentifierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AccountBalanceDetailType PointsStatementListItem {
            get {
                return this.pointsStatementListItemField;
            }
            set {
                this.pointsStatementListItemField = value;
                this.RaisePropertyChanged("PointsStatementListItem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public EnrollmentStatusType EnrollmentStatus {
            get {
                return this.enrollmentStatusField;
            }
            set {
                this.enrollmentStatusField = value;
                this.RaisePropertyChanged("EnrollmentStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RedemptionOptionListItem", Order=2)]
        public RedemptionOptionDisplayType[] RedemptionOptionListItem {
            get {
                return this.redemptionOptionListItemField;
            }
            set {
                this.redemptionOptionListItemField = value;
                this.RaisePropertyChanged("RedemptionOptionListItem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MembershipIdentifier {
            get {
                return this.membershipIdentifierField;
            }
            set {
                this.membershipIdentifierField = value;
                this.RaisePropertyChanged("MembershipIdentifier");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.payback.net/lmsglobal/xsd/v1/types")]
    public enum EnrollmentStatusType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAliasDashboardRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.payback.net/lmsglobal/ws/v1/extint/types", Order=0)]
        public WebPOS.WsRedemption.GetAliasDashboardRequest GetAliasDashboardRequest;
        
        public GetAliasDashboardRequest1() {
        }
        
        public GetAliasDashboardRequest1(WebPOS.WsRedemption.GetAliasDashboardRequest GetAliasDashboardRequest) {
            this.GetAliasDashboardRequest = GetAliasDashboardRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAliasDashboardResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.payback.net/lmsglobal/ws/v1/extint/types", Order=0)]
        public WebPOS.WsRedemption.GetAliasDashboardResponse GetAliasDashboardResponse;
        
        public GetAliasDashboardResponse1() {
        }
        
        public GetAliasDashboardResponse1(WebPOS.WsRedemption.GetAliasDashboardResponse GetAliasDashboardResponse) {
            this.GetAliasDashboardResponse = GetAliasDashboardResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.payback.net/lmsglobal/ws/v1/extint/types")]
    public partial class ProcessDirectRedemptionEventRequest : AuthorisedRequest {
        
        private MemberAliasAuthenticationType authenticationField;
        
        private RedemptionEventType redemptionEventField;
        
        private DirectRedemptionItemDetails directRedemptionItemDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MemberAliasAuthenticationType Authentication {
            get {
                return this.authenticationField;
            }
            set {
                this.authenticationField = value;
                this.RaisePropertyChanged("Authentication");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public RedemptionEventType RedemptionEvent {
            get {
                return this.redemptionEventField;
            }
            set {
                this.redemptionEventField = value;
                this.RaisePropertyChanged("RedemptionEvent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public DirectRedemptionItemDetails DirectRedemptionItemDetails {
            get {
                return this.directRedemptionItemDetailsField;
            }
            set {
                this.directRedemptionItemDetailsField = value;
                this.RaisePropertyChanged("DirectRedemptionItemDetails");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.payback.net/lmsglobal/ws/v1/extint/types")]
    public partial class ProcessDirectRedemptionEventResponse : MessageResponse {
        
        private string redemptionNumberField;
        
        private AccountBalanceDetailType accountBalanceDetailsField;
        
        private TransactionDetails[] transactionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RedemptionNumber {
            get {
                return this.redemptionNumberField;
            }
            set {
                this.redemptionNumberField = value;
                this.RaisePropertyChanged("RedemptionNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public AccountBalanceDetailType AccountBalanceDetails {
            get {
                return this.accountBalanceDetailsField;
            }
            set {
                this.accountBalanceDetailsField = value;
                this.RaisePropertyChanged("AccountBalanceDetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Transactions", Order=2)]
        public TransactionDetails[] Transactions {
            get {
                return this.transactionsField;
            }
            set {
                this.transactionsField = value;
                this.RaisePropertyChanged("Transactions");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessDirectRedemptionEventRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.payback.net/lmsglobal/ws/v1/extint/types", Order=0)]
        public WebPOS.WsRedemption.ProcessDirectRedemptionEventRequest ProcessDirectRedemptionEventRequest;
        
        public ProcessDirectRedemptionEventRequest1() {
        }
        
        public ProcessDirectRedemptionEventRequest1(WebPOS.WsRedemption.ProcessDirectRedemptionEventRequest ProcessDirectRedemptionEventRequest) {
            this.ProcessDirectRedemptionEventRequest = ProcessDirectRedemptionEventRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessDirectRedemptionEventResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.payback.net/lmsglobal/ws/v1/extint/types", Order=0)]
        public WebPOS.WsRedemption.ProcessDirectRedemptionEventResponse ProcessDirectRedemptionEventResponse;
        
        public ProcessDirectRedemptionEventResponse1() {
        }
        
        public ProcessDirectRedemptionEventResponse1(WebPOS.WsRedemption.ProcessDirectRedemptionEventResponse ProcessDirectRedemptionEventResponse) {
            this.ProcessDirectRedemptionEventResponse = ProcessDirectRedemptionEventResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.payback.net/lmsglobal/ws/v1/extint/types")]
    public partial class RefundDirectRedemptionEventRequest : AuthorisedRequest {
        
        private MemberAliasIdentificationType authenticationField;
        
        private RedemptionEventType redemptionEventField;
        
        private string redemptionNumberField;
        
        private DirectRedemptionItemDetails directRedemptionItemDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MemberAliasIdentificationType Authentication {
            get {
                return this.authenticationField;
            }
            set {
                this.authenticationField = value;
                this.RaisePropertyChanged("Authentication");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public RedemptionEventType RedemptionEvent {
            get {
                return this.redemptionEventField;
            }
            set {
                this.redemptionEventField = value;
                this.RaisePropertyChanged("RedemptionEvent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string RedemptionNumber {
            get {
                return this.redemptionNumberField;
            }
            set {
                this.redemptionNumberField = value;
                this.RaisePropertyChanged("RedemptionNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public DirectRedemptionItemDetails DirectRedemptionItemDetails {
            get {
                return this.directRedemptionItemDetailsField;
            }
            set {
                this.directRedemptionItemDetailsField = value;
                this.RaisePropertyChanged("DirectRedemptionItemDetails");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.payback.net/lmsglobal/ws/v1/extint/types")]
    public partial class RefundDirectRedemptionEventResponse : MessageResponse {
        
        private AccountBalanceDetailType accountBalanceDetailsField;
        
        private TransactionDetails[] transactionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AccountBalanceDetailType AccountBalanceDetails {
            get {
                return this.accountBalanceDetailsField;
            }
            set {
                this.accountBalanceDetailsField = value;
                this.RaisePropertyChanged("AccountBalanceDetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Transactions", Order=1)]
        public TransactionDetails[] Transactions {
            get {
                return this.transactionsField;
            }
            set {
                this.transactionsField = value;
                this.RaisePropertyChanged("Transactions");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RefundDirectRedemptionEventRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.payback.net/lmsglobal/ws/v1/extint/types", Order=0)]
        public WebPOS.WsRedemption.RefundDirectRedemptionEventRequest RefundDirectRedemptionEventRequest;
        
        public RefundDirectRedemptionEventRequest1() {
        }
        
        public RefundDirectRedemptionEventRequest1(WebPOS.WsRedemption.RefundDirectRedemptionEventRequest RefundDirectRedemptionEventRequest) {
            this.RefundDirectRedemptionEventRequest = RefundDirectRedemptionEventRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RefundDirectRedemptionEventResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.payback.net/lmsglobal/ws/v1/extint/types", Order=0)]
        public WebPOS.WsRedemption.RefundDirectRedemptionEventResponse RefundDirectRedemptionEventResponse;
        
        public RefundDirectRedemptionEventResponse1() {
        }
        
        public RefundDirectRedemptionEventResponse1(WebPOS.WsRedemption.RefundDirectRedemptionEventResponse RefundDirectRedemptionEventResponse) {
            this.RefundDirectRedemptionEventResponse = RefundDirectRedemptionEventResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.payback.net/lmsglobal/ws/v1/extint/types")]
    public partial class ReverseRedemptionEventRequest : AuthorisedRequest {
        
        private MemberAliasIdentificationType authenticationField;
        
        private RedemptionEventType redemptionEventField;
        
        private string redemptionNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MemberAliasIdentificationType Authentication {
            get {
                return this.authenticationField;
            }
            set {
                this.authenticationField = value;
                this.RaisePropertyChanged("Authentication");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public RedemptionEventType RedemptionEvent {
            get {
                return this.redemptionEventField;
            }
            set {
                this.redemptionEventField = value;
                this.RaisePropertyChanged("RedemptionEvent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string RedemptionNumber {
            get {
                return this.redemptionNumberField;
            }
            set {
                this.redemptionNumberField = value;
                this.RaisePropertyChanged("RedemptionNumber");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.payback.net/lmsglobal/ws/v1/extint/types")]
    public partial class ReverseRedemptionEventResponse : MessageResponse {
        
        private AccountBalanceDetailType accountBalanceDetailsField;
        
        private TransactionDetails[] transactionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AccountBalanceDetailType AccountBalanceDetails {
            get {
                return this.accountBalanceDetailsField;
            }
            set {
                this.accountBalanceDetailsField = value;
                this.RaisePropertyChanged("AccountBalanceDetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Transactions", Order=1)]
        public TransactionDetails[] Transactions {
            get {
                return this.transactionsField;
            }
            set {
                this.transactionsField = value;
                this.RaisePropertyChanged("Transactions");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReverseRedemptionEventRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.payback.net/lmsglobal/ws/v1/extint/types", Order=0)]
        public WebPOS.WsRedemption.ReverseRedemptionEventRequest ReverseRedemptionEventRequest;
        
        public ReverseRedemptionEventRequest1() {
        }
        
        public ReverseRedemptionEventRequest1(WebPOS.WsRedemption.ReverseRedemptionEventRequest ReverseRedemptionEventRequest) {
            this.ReverseRedemptionEventRequest = ReverseRedemptionEventRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReverseRedemptionEventResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.payback.net/lmsglobal/ws/v1/extint/types", Order=0)]
        public WebPOS.WsRedemption.ReverseRedemptionEventResponse ReverseRedemptionEventResponse;
        
        public ReverseRedemptionEventResponse1() {
        }
        
        public ReverseRedemptionEventResponse1(WebPOS.WsRedemption.ReverseRedemptionEventResponse ReverseRedemptionEventResponse) {
            this.ReverseRedemptionEventResponse = ReverseRedemptionEventResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ExtintPortTypeChannel : WebPOS.WsRedemption.ExtintPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExtintPortTypeClient : System.ServiceModel.ClientBase<WebPOS.WsRedemption.ExtintPortType>, WebPOS.WsRedemption.ExtintPortType {
        
        public ExtintPortTypeClient() {
        }
        
        public ExtintPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExtintPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExtintPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExtintPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebPOS.WsRedemption.GetAliasDashboardResponse1 WebPOS.WsRedemption.ExtintPortType.GetAliasDashboard(WebPOS.WsRedemption.GetAliasDashboardRequest1 request) {
            return base.Channel.GetAliasDashboard(request);
        }
        
        public WebPOS.WsRedemption.GetAliasDashboardResponse GetAliasDashboard(WebPOS.WsRedemption.GetAliasDashboardRequest GetAliasDashboardRequest) {
            WebPOS.WsRedemption.GetAliasDashboardRequest1 inValue = new WebPOS.WsRedemption.GetAliasDashboardRequest1();
            inValue.GetAliasDashboardRequest = GetAliasDashboardRequest;
            WebPOS.WsRedemption.GetAliasDashboardResponse1 retVal = ((WebPOS.WsRedemption.ExtintPortType)(this)).GetAliasDashboard(inValue);
            return retVal.GetAliasDashboardResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebPOS.WsRedemption.GetAliasDashboardResponse1> WebPOS.WsRedemption.ExtintPortType.GetAliasDashboardAsync(WebPOS.WsRedemption.GetAliasDashboardRequest1 request) {
            return base.Channel.GetAliasDashboardAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebPOS.WsRedemption.GetAliasDashboardResponse1> GetAliasDashboardAsync(WebPOS.WsRedemption.GetAliasDashboardRequest GetAliasDashboardRequest) {
            WebPOS.WsRedemption.GetAliasDashboardRequest1 inValue = new WebPOS.WsRedemption.GetAliasDashboardRequest1();
            inValue.GetAliasDashboardRequest = GetAliasDashboardRequest;
            return ((WebPOS.WsRedemption.ExtintPortType)(this)).GetAliasDashboardAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebPOS.WsRedemption.ProcessDirectRedemptionEventResponse1 WebPOS.WsRedemption.ExtintPortType.ProcessDirectRedemptionEvent(WebPOS.WsRedemption.ProcessDirectRedemptionEventRequest1 request) {
            return base.Channel.ProcessDirectRedemptionEvent(request);
        }
        
        public WebPOS.WsRedemption.ProcessDirectRedemptionEventResponse ProcessDirectRedemptionEvent(WebPOS.WsRedemption.ProcessDirectRedemptionEventRequest ProcessDirectRedemptionEventRequest) {
            WebPOS.WsRedemption.ProcessDirectRedemptionEventRequest1 inValue = new WebPOS.WsRedemption.ProcessDirectRedemptionEventRequest1();
            inValue.ProcessDirectRedemptionEventRequest = ProcessDirectRedemptionEventRequest;
            WebPOS.WsRedemption.ProcessDirectRedemptionEventResponse1 retVal = ((WebPOS.WsRedemption.ExtintPortType)(this)).ProcessDirectRedemptionEvent(inValue);
            return retVal.ProcessDirectRedemptionEventResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebPOS.WsRedemption.ProcessDirectRedemptionEventResponse1> WebPOS.WsRedemption.ExtintPortType.ProcessDirectRedemptionEventAsync(WebPOS.WsRedemption.ProcessDirectRedemptionEventRequest1 request) {
            return base.Channel.ProcessDirectRedemptionEventAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebPOS.WsRedemption.ProcessDirectRedemptionEventResponse1> ProcessDirectRedemptionEventAsync(WebPOS.WsRedemption.ProcessDirectRedemptionEventRequest ProcessDirectRedemptionEventRequest) {
            WebPOS.WsRedemption.ProcessDirectRedemptionEventRequest1 inValue = new WebPOS.WsRedemption.ProcessDirectRedemptionEventRequest1();
            inValue.ProcessDirectRedemptionEventRequest = ProcessDirectRedemptionEventRequest;
            return ((WebPOS.WsRedemption.ExtintPortType)(this)).ProcessDirectRedemptionEventAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebPOS.WsRedemption.RefundDirectRedemptionEventResponse1 WebPOS.WsRedemption.ExtintPortType.RefundDirectRedemptionEvent(WebPOS.WsRedemption.RefundDirectRedemptionEventRequest1 request) {
            return base.Channel.RefundDirectRedemptionEvent(request);
        }
        
        public WebPOS.WsRedemption.RefundDirectRedemptionEventResponse RefundDirectRedemptionEvent(WebPOS.WsRedemption.RefundDirectRedemptionEventRequest RefundDirectRedemptionEventRequest) {
            WebPOS.WsRedemption.RefundDirectRedemptionEventRequest1 inValue = new WebPOS.WsRedemption.RefundDirectRedemptionEventRequest1();
            inValue.RefundDirectRedemptionEventRequest = RefundDirectRedemptionEventRequest;
            WebPOS.WsRedemption.RefundDirectRedemptionEventResponse1 retVal = ((WebPOS.WsRedemption.ExtintPortType)(this)).RefundDirectRedemptionEvent(inValue);
            return retVal.RefundDirectRedemptionEventResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebPOS.WsRedemption.RefundDirectRedemptionEventResponse1> WebPOS.WsRedemption.ExtintPortType.RefundDirectRedemptionEventAsync(WebPOS.WsRedemption.RefundDirectRedemptionEventRequest1 request) {
            return base.Channel.RefundDirectRedemptionEventAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebPOS.WsRedemption.RefundDirectRedemptionEventResponse1> RefundDirectRedemptionEventAsync(WebPOS.WsRedemption.RefundDirectRedemptionEventRequest RefundDirectRedemptionEventRequest) {
            WebPOS.WsRedemption.RefundDirectRedemptionEventRequest1 inValue = new WebPOS.WsRedemption.RefundDirectRedemptionEventRequest1();
            inValue.RefundDirectRedemptionEventRequest = RefundDirectRedemptionEventRequest;
            return ((WebPOS.WsRedemption.ExtintPortType)(this)).RefundDirectRedemptionEventAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebPOS.WsRedemption.ReverseRedemptionEventResponse1 WebPOS.WsRedemption.ExtintPortType.ReverseRedemptionEvent(WebPOS.WsRedemption.ReverseRedemptionEventRequest1 request) {
            return base.Channel.ReverseRedemptionEvent(request);
        }
        
        public WebPOS.WsRedemption.ReverseRedemptionEventResponse ReverseRedemptionEvent(WebPOS.WsRedemption.ReverseRedemptionEventRequest ReverseRedemptionEventRequest) {
            WebPOS.WsRedemption.ReverseRedemptionEventRequest1 inValue = new WebPOS.WsRedemption.ReverseRedemptionEventRequest1();
            inValue.ReverseRedemptionEventRequest = ReverseRedemptionEventRequest;
            WebPOS.WsRedemption.ReverseRedemptionEventResponse1 retVal = ((WebPOS.WsRedemption.ExtintPortType)(this)).ReverseRedemptionEvent(inValue);
            return retVal.ReverseRedemptionEventResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebPOS.WsRedemption.ReverseRedemptionEventResponse1> WebPOS.WsRedemption.ExtintPortType.ReverseRedemptionEventAsync(WebPOS.WsRedemption.ReverseRedemptionEventRequest1 request) {
            return base.Channel.ReverseRedemptionEventAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebPOS.WsRedemption.ReverseRedemptionEventResponse1> ReverseRedemptionEventAsync(WebPOS.WsRedemption.ReverseRedemptionEventRequest ReverseRedemptionEventRequest) {
            WebPOS.WsRedemption.ReverseRedemptionEventRequest1 inValue = new WebPOS.WsRedemption.ReverseRedemptionEventRequest1();
            inValue.ReverseRedemptionEventRequest = ReverseRedemptionEventRequest;
            return ((WebPOS.WsRedemption.ExtintPortType)(this)).ReverseRedemptionEventAsync(inValue);
        }
    }
}
