//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPOS.WsMessage {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsMessage.WsMessageSoap")]
    public interface WsMessageSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento numberUser del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecibeDateMessage", ReplyAction="*")]
        WebPOS.WsMessage.RecibeDateMessageResponse RecibeDateMessage(WebPOS.WsMessage.RecibeDateMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecibeDateMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<WebPOS.WsMessage.RecibeDateMessageResponse> RecibeDateMessageAsync(WebPOS.WsMessage.RecibeDateMessageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecibeDateMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RecibeDateMessage", Namespace="http://tempuri.org/", Order=0)]
        public WebPOS.WsMessage.RecibeDateMessageRequestBody Body;
        
        public RecibeDateMessageRequest() {
        }
        
        public RecibeDateMessageRequest(WebPOS.WsMessage.RecibeDateMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RecibeDateMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idEnvio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string numberUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string messageUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string emailUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string numberClient;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string emailClient;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string messageClient;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int idclient;
        
        public RecibeDateMessageRequestBody() {
        }
        
        public RecibeDateMessageRequestBody(int idEnvio, string numberUser, string messageUser, string emailUser, string numberClient, string emailClient, string messageClient, int idclient) {
            this.idEnvio = idEnvio;
            this.numberUser = numberUser;
            this.messageUser = messageUser;
            this.emailUser = emailUser;
            this.numberClient = numberClient;
            this.emailClient = emailClient;
            this.messageClient = messageClient;
            this.idclient = idclient;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecibeDateMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RecibeDateMessageResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebPOS.WsMessage.RecibeDateMessageResponseBody Body;
        
        public RecibeDateMessageResponse() {
        }
        
        public RecibeDateMessageResponse(WebPOS.WsMessage.RecibeDateMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RecibeDateMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebPOS.WsMessage.ArrayOfString RecibeDateMessageResult;
        
        public RecibeDateMessageResponseBody() {
        }
        
        public RecibeDateMessageResponseBody(WebPOS.WsMessage.ArrayOfString RecibeDateMessageResult) {
            this.RecibeDateMessageResult = RecibeDateMessageResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WsMessageSoapChannel : WebPOS.WsMessage.WsMessageSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsMessageSoapClient : System.ServiceModel.ClientBase<WebPOS.WsMessage.WsMessageSoap>, WebPOS.WsMessage.WsMessageSoap {
        
        public WsMessageSoapClient() {
        }
        
        public WsMessageSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsMessageSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsMessageSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsMessageSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebPOS.WsMessage.RecibeDateMessageResponse WebPOS.WsMessage.WsMessageSoap.RecibeDateMessage(WebPOS.WsMessage.RecibeDateMessageRequest request) {
            return base.Channel.RecibeDateMessage(request);
        }
        
        public WebPOS.WsMessage.ArrayOfString RecibeDateMessage(int idEnvio, string numberUser, string messageUser, string emailUser, string numberClient, string emailClient, string messageClient, int idclient) {
            WebPOS.WsMessage.RecibeDateMessageRequest inValue = new WebPOS.WsMessage.RecibeDateMessageRequest();
            inValue.Body = new WebPOS.WsMessage.RecibeDateMessageRequestBody();
            inValue.Body.idEnvio = idEnvio;
            inValue.Body.numberUser = numberUser;
            inValue.Body.messageUser = messageUser;
            inValue.Body.emailUser = emailUser;
            inValue.Body.numberClient = numberClient;
            inValue.Body.emailClient = emailClient;
            inValue.Body.messageClient = messageClient;
            inValue.Body.idclient = idclient;
            WebPOS.WsMessage.RecibeDateMessageResponse retVal = ((WebPOS.WsMessage.WsMessageSoap)(this)).RecibeDateMessage(inValue);
            return retVal.Body.RecibeDateMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebPOS.WsMessage.RecibeDateMessageResponse> WebPOS.WsMessage.WsMessageSoap.RecibeDateMessageAsync(WebPOS.WsMessage.RecibeDateMessageRequest request) {
            return base.Channel.RecibeDateMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebPOS.WsMessage.RecibeDateMessageResponse> RecibeDateMessageAsync(int idEnvio, string numberUser, string messageUser, string emailUser, string numberClient, string emailClient, string messageClient, int idclient) {
            WebPOS.WsMessage.RecibeDateMessageRequest inValue = new WebPOS.WsMessage.RecibeDateMessageRequest();
            inValue.Body = new WebPOS.WsMessage.RecibeDateMessageRequestBody();
            inValue.Body.idEnvio = idEnvio;
            inValue.Body.numberUser = numberUser;
            inValue.Body.messageUser = messageUser;
            inValue.Body.emailUser = emailUser;
            inValue.Body.numberClient = numberClient;
            inValue.Body.emailClient = emailClient;
            inValue.Body.messageClient = messageClient;
            inValue.Body.idclient = idclient;
            return ((WebPOS.WsMessage.WsMessageSoap)(this)).RecibeDateMessageAsync(inValue);
        }
    }
}
