//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPOS.WsAcumulation {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.payback.net/lmsglobal/ws/v1/extint", ConfigurationName="WsAcumulation.ExtintPortType")]
    public interface ExtintPortType {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación GetCouponsOnReceipt no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="GetCouponsOnReceipt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessageResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AuthorisedRequest))]
        WebPOS.WsAcumulation.GetCouponsOnReceiptResponse1 GetCouponsOnReceipt(WebPOS.WsAcumulation.GetCouponsOnReceiptRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetCouponsOnReceipt", ReplyAction="*")]
        System.Threading.Tasks.Task<WebPOS.WsAcumulation.GetCouponsOnReceiptResponse1> GetCouponsOnReceiptAsync(WebPOS.WsAcumulation.GetCouponsOnReceiptRequest1 request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación ProcessPurchaseAndPromotionEvent no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="ProcessPurchaseAndPromotionEvent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessageResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AuthorisedRequest))]
        WebPOS.WsAcumulation.ProcessPurchaseAndPromotionEventResponse1 ProcessPurchaseAndPromotionEvent(WebPOS.WsAcumulation.ProcessPurchaseAndPromotionEventRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="ProcessPurchaseAndPromotionEvent", ReplyAction="*")]
        System.Threading.Tasks.Task<WebPOS.WsAcumulation.ProcessPurchaseAndPromotionEventResponse1> ProcessPurchaseAndPromotionEventAsync(WebPOS.WsAcumulation.ProcessPurchaseAndPromotionEventRequest1 request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación RefundPurchaseEvent no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="RefundPurchaseEvent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessageResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AuthorisedRequest))]
        WebPOS.WsAcumulation.RefundPurchaseEventResponse1 RefundPurchaseEvent(WebPOS.WsAcumulation.RefundPurchaseEventRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="RefundPurchaseEvent", ReplyAction="*")]
        System.Threading.Tasks.Task<WebPOS.WsAcumulation.RefundPurchaseEventResponse1> RefundPurchaseEventAsync(WebPOS.WsAcumulation.RefundPurchaseEventRequest1 request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación ReverseCollectEvent no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="ReverseCollectEvent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessageResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AuthorisedRequest))]
        WebPOS.WsAcumulation.ReverseCollectEventResponse1 ReverseCollectEvent(WebPOS.WsAcumulation.ReverseCollectEventRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="ReverseCollectEvent", ReplyAction="*")]
        System.Threading.Tasks.Task<WebPOS.WsAcumulation.ReverseCollectEventResponse1> ReverseCollectEventAsync(WebPOS.WsAcumulation.ReverseCollectEventRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.payback.net/lmsglobal/ws/v1/extint/types")]
    public partial class GetCouponsOnReceiptRequest : AuthorisedRequest {
        
        private MemberAliasIdentificationType authenticationField;
        
        private System.DateTime referenceDateField;
        
        private PartnerContextType[] couponFilterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MemberAliasIdentificationType Authentication {
            get {
                return this.authenticationField;
            }
            set {
                this.authenticationField = value;
                this.RaisePropertyChanged("Authentication");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime ReferenceDate {
            get {
                return this.referenceDateField;
            }
            set {
                this.referenceDateField = value;
                this.RaisePropertyChanged("ReferenceDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Partner", Namespace="http://www.payback.net/lmsglobal/xsd/v1/types", IsNullable=false)]
        public PartnerContextType[] CouponFilter {
            get {
                return this.couponFilterField;
            }
            set {
                this.couponFilterField = value;
                this.RaisePropertyChanged("CouponFilter");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.payback.net/lmsglobal/xsd/v1/types")]
    public partial class MemberAliasIdentificationType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MemberIdentificationType identificationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MemberIdentificationType Identification {
            get {
                return this.identificationField;
            }
            set {
                this.identificationField = value;
                this.RaisePropertyChanged("Identification");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.payback.net/lmsglobal/xsd/v1/types")]
    public partial class MemberIdentificationType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string aliasField;
        
        private PrincipalVariantType aliasTypeField;
        
        private bool aliasTypeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
                this.RaisePropertyChanged("Alias");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public PrincipalVariantType AliasType {
            get {
                return this.aliasTypeField;
            }
            set {
                this.aliasTypeField = value;
                this.RaisePropertyChanged("AliasType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AliasTypeSpecified {
            get {
                return this.aliasTypeFieldSpecified;
            }
            set {
                this.aliasTypeFieldSpecified = value;
                this.RaisePropertyChanged("AliasTypeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.payback.net/lmsglobal/xsd/v1/types")]
    public enum PrincipalVariantType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.payback.net/lmsglobal/xsd/v1/types")]
    public partial class PromotionDetailsType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LoyaltyUnitType loyaltyValueField;
        
        private string marketingCodeField;
        
        private string marketingCodeDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public LoyaltyUnitType LoyaltyValue {
            get {
                return this.loyaltyValueField;
            }
            set {
                this.loyaltyValueField = value;
                this.RaisePropertyChanged("LoyaltyValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MarketingCode {
            get {
                return this.marketingCodeField;
            }
            set {
                this.marketingCodeField = value;
                this.RaisePropertyChanged("MarketingCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MarketingCodeDescription {
            get {
                return this.marketingCodeDescriptionField;
            }
            set {
                this.marketingCodeDescriptionField = value;
                this.RaisePropertyChanged("MarketingCodeDescription");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.payback.net/lmsglobal/xsd/v1/types")]
    public partial class LoyaltyUnitType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal loyaltyAmountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal LoyaltyAmount {
            get {
                return this.loyaltyAmountField;
            }
            set {
                this.loyaltyAmountField = value;
                this.RaisePropertyChanged("LoyaltyAmount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.payback.net/lmsglobal/xsd/v1/types")]
    public partial class CollectionInformationType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LoyaltyUnitType[] baseLoyaltyValueField;
        
        private LoyaltyUnitType[] promotionLoyaltyValueField;
        
        private PromotionDetailsType[] promotionDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BaseLoyaltyValue", Order=0)]
        public LoyaltyUnitType[] BaseLoyaltyValue {
            get {
                return this.baseLoyaltyValueField;
            }
            set {
                this.baseLoyaltyValueField = value;
                this.RaisePropertyChanged("BaseLoyaltyValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PromotionLoyaltyValue", Order=1)]
        public LoyaltyUnitType[] PromotionLoyaltyValue {
            get {
                return this.promotionLoyaltyValueField;
            }
            set {
                this.promotionLoyaltyValueField = value;
                this.RaisePropertyChanged("PromotionLoyaltyValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PromotionDetails", Order=2)]
        public PromotionDetailsType[] PromotionDetails {
            get {
                return this.promotionDetailsField;
            }
            set {
                this.promotionDetailsField = value;
                this.RaisePropertyChanged("PromotionDetails");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.payback.net/lmsglobal/xsd/v1/types")]
    public partial class ExpiryStatisticsType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal expiredPointsAmountField;
        
        private System.DateTime expiredSinceDateField;
        
        private bool expiredSinceDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal ExpiredPointsAmount {
            get {
                return this.expiredPointsAmountField;
            }
            set {
                this.expiredPointsAmountField = value;
                this.RaisePropertyChanged("ExpiredPointsAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime ExpiredSinceDate {
            get {
                return this.expiredSinceDateField;
            }
            set {
                this.expiredSinceDateField = value;
                this.RaisePropertyChanged("ExpiredSinceDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpiredSinceDateSpecified {
            get {
                return this.expiredSinceDateFieldSpecified;
            }
            set {
                this.expiredSinceDateFieldSpecified = value;
                this.RaisePropertyChanged("ExpiredSinceDateSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.payback.net/lmsglobal/xsd/v1/types")]
    public partial class ExpiryAnnouncementType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal pointsToExpireAmountField;
        
        private System.DateTime nextExpiryDateField;
        
        private bool nextExpiryDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal PointsToExpireAmount {
            get {
                return this.pointsToExpireAmountField;
            }
            set {
                this.pointsToExpireAmountField = value;
                this.RaisePropertyChanged("PointsToExpireAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime NextExpiryDate {
            get {
                return this.nextExpiryDateField;
            }
            set {
                this.nextExpiryDateField = value;
                this.RaisePropertyChanged("NextExpiryDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NextExpiryDateSpecified {
            get {
                return this.nextExpiryDateFieldSpecified;
            }
            set {
                this.nextExpiryDateFieldSpecified = value;
                this.RaisePropertyChanged("NextExpiryDateSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.payback.net/lmsglobal/xsd/v1/types")]
    public partial class AccountBalanceDetailType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal totalPointsAmountField;
        
        private decimal availablePointsAmountField;
        
        private decimal blockedPointsAmountField;
        
        private ExpiryAnnouncementType expiryAnnouncementField;
        
        private ExpiryStatisticsType expiryStatisticsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal TotalPointsAmount {
            get {
                return this.totalPointsAmountField;
            }
            set {
                this.totalPointsAmountField = value;
                this.RaisePropertyChanged("TotalPointsAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal AvailablePointsAmount {
            get {
                return this.availablePointsAmountField;
            }
            set {
                this.availablePointsAmountField = value;
                this.RaisePropertyChanged("AvailablePointsAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal BlockedPointsAmount {
            get {
                return this.blockedPointsAmountField;
            }
            set {
                this.blockedPointsAmountField = value;
                this.RaisePropertyChanged("BlockedPointsAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public ExpiryAnnouncementType ExpiryAnnouncement {
            get {
                return this.expiryAnnouncementField;
            }
            set {
                this.expiryAnnouncementField = value;
                this.RaisePropertyChanged("ExpiryAnnouncement");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public ExpiryStatisticsType ExpiryStatistics {
            get {
                return this.expiryStatisticsField;
            }
            set {
                this.expiryStatisticsField = value;
                this.RaisePropertyChanged("ExpiryStatistics");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.payback.net/lmsglobal/xsd/v1/types")]
    public partial class ReferencePurchaseDetailsType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LegalUnitType rewardableLegalValueField;
        
        private string receiptNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public LegalUnitType RewardableLegalValue {
            get {
                return this.rewardableLegalValueField;
            }
            set {
                this.rewardableLegalValueField = value;
                this.RaisePropertyChanged("RewardableLegalValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ReceiptNumber {
            get {
                return this.receiptNumberField;
            }
            set {
                this.receiptNumberField = value;
                this.RaisePropertyChanged("ReceiptNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.payback.net/lmsglobal/xsd/v1/types")]
    public partial class LegalUnitType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal legalAmountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal LegalAmount {
            get {
                return this.legalAmountField;
            }
            set {
                this.legalAmountField = value;
                this.RaisePropertyChanged("LegalAmount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.payback.net/lmsglobal/xsd/v1/types")]
    public partial class TransactionDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int transactionTypeField;
        
        private string marketingCodeField;
        
        private LoyaltyUnitType totalPointsField;
        
        private System.DateTime pointsBlockedUntilField;
        
        private bool pointsBlockedUntilFieldSpecified;
        
        private double vATRateField;
        
        private bool vATRateFieldSpecified;
        
        private ReferencePurchaseDetailsType[] referencePurchaseDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int TransactionType {
            get {
                return this.transactionTypeField;
            }
            set {
                this.transactionTypeField = value;
                this.RaisePropertyChanged("TransactionType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MarketingCode {
            get {
                return this.marketingCodeField;
            }
            set {
                this.marketingCodeField = value;
                this.RaisePropertyChanged("MarketingCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public LoyaltyUnitType TotalPoints {
            get {
                return this.totalPointsField;
            }
            set {
                this.totalPointsField = value;
                this.RaisePropertyChanged("TotalPoints");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime PointsBlockedUntil {
            get {
                return this.pointsBlockedUntilField;
            }
            set {
                this.pointsBlockedUntilField = value;
                this.RaisePropertyChanged("PointsBlockedUntil");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PointsBlockedUntilSpecified {
            get {
                return this.pointsBlockedUntilFieldSpecified;
            }
            set {
                this.pointsBlockedUntilFieldSpecified = value;
                this.RaisePropertyChanged("PointsBlockedUntilSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public double VATRate {
            get {
                return this.vATRateField;
            }
            set {
                this.vATRateField = value;
                this.RaisePropertyChanged("VATRate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VATRateSpecified {
            get {
                return this.vATRateFieldSpecified;
            }
            set {
                this.vATRateFieldSpecified = value;
                this.RaisePropertyChanged("VATRateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ReferencePurchaseDetails", Order=5)]
        public ReferencePurchaseDetailsType[] ReferencePurchaseDetails {
            get {
                return this.referencePurchaseDetailsField;
            }
            set {
                this.referencePurchaseDetailsField = value;
                this.RaisePropertyChanged("ReferencePurchaseDetails");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.payback.net/lmsglobal/xsd/v1/types")]
    public partial class PurchaseItemDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal pointsAmountField;
        
        private bool pointsAmountFieldSpecified;
        
        private string articleDescriptionField;
        
        private string articleEanCodeField;
        
        private string partnerProductGroupCodeField;
        
        private string partnerProductGroupNameField;
        
        private string partnerProductCategoryCodeField;
        
        private string partnerProductCategoryNameField;
        
        private string supplierCodeField;
        
        private string supplierNameField;
        
        private decimal singleTurnoverAmountField;
        
        private bool singleTurnoverAmountFieldSpecified;
        
        private decimal quantityField;
        
        private bool quantityFieldSpecified;
        
        private string quantityUnitCodeField;
        
        private decimal totalTurnoverAmountField;
        
        private bool totalTurnoverAmountFieldSpecified;
        
        private decimal totalRewardableAmountField;
        
        private bool totalRewardableAmountFieldSpecified;
        
        private decimal vatAmountField;
        
        private bool vatAmountFieldSpecified;
        
        private double vATRateField;
        
        private bool vATRateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal PointsAmount {
            get {
                return this.pointsAmountField;
            }
            set {
                this.pointsAmountField = value;
                this.RaisePropertyChanged("PointsAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PointsAmountSpecified {
            get {
                return this.pointsAmountFieldSpecified;
            }
            set {
                this.pointsAmountFieldSpecified = value;
                this.RaisePropertyChanged("PointsAmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ArticleDescription {
            get {
                return this.articleDescriptionField;
            }
            set {
                this.articleDescriptionField = value;
                this.RaisePropertyChanged("ArticleDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ArticleEanCode {
            get {
                return this.articleEanCodeField;
            }
            set {
                this.articleEanCodeField = value;
                this.RaisePropertyChanged("ArticleEanCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string PartnerProductGroupCode {
            get {
                return this.partnerProductGroupCodeField;
            }
            set {
                this.partnerProductGroupCodeField = value;
                this.RaisePropertyChanged("PartnerProductGroupCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string PartnerProductGroupName {
            get {
                return this.partnerProductGroupNameField;
            }
            set {
                this.partnerProductGroupNameField = value;
                this.RaisePropertyChanged("PartnerProductGroupName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string PartnerProductCategoryCode {
            get {
                return this.partnerProductCategoryCodeField;
            }
            set {
                this.partnerProductCategoryCodeField = value;
                this.RaisePropertyChanged("PartnerProductCategoryCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string PartnerProductCategoryName {
            get {
                return this.partnerProductCategoryNameField;
            }
            set {
                this.partnerProductCategoryNameField = value;
                this.RaisePropertyChanged("PartnerProductCategoryName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string SupplierCode {
            get {
                return this.supplierCodeField;
            }
            set {
                this.supplierCodeField = value;
                this.RaisePropertyChanged("SupplierCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string SupplierName {
            get {
                return this.supplierNameField;
            }
            set {
                this.supplierNameField = value;
                this.RaisePropertyChanged("SupplierName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public decimal SingleTurnoverAmount {
            get {
                return this.singleTurnoverAmountField;
            }
            set {
                this.singleTurnoverAmountField = value;
                this.RaisePropertyChanged("SingleTurnoverAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SingleTurnoverAmountSpecified {
            get {
                return this.singleTurnoverAmountFieldSpecified;
            }
            set {
                this.singleTurnoverAmountFieldSpecified = value;
                this.RaisePropertyChanged("SingleTurnoverAmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public decimal Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("Quantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuantitySpecified {
            get {
                return this.quantityFieldSpecified;
            }
            set {
                this.quantityFieldSpecified = value;
                this.RaisePropertyChanged("QuantitySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string QuantityUnitCode {
            get {
                return this.quantityUnitCodeField;
            }
            set {
                this.quantityUnitCodeField = value;
                this.RaisePropertyChanged("QuantityUnitCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public decimal TotalTurnoverAmount {
            get {
                return this.totalTurnoverAmountField;
            }
            set {
                this.totalTurnoverAmountField = value;
                this.RaisePropertyChanged("TotalTurnoverAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalTurnoverAmountSpecified {
            get {
                return this.totalTurnoverAmountFieldSpecified;
            }
            set {
                this.totalTurnoverAmountFieldSpecified = value;
                this.RaisePropertyChanged("TotalTurnoverAmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public decimal TotalRewardableAmount {
            get {
                return this.totalRewardableAmountField;
            }
            set {
                this.totalRewardableAmountField = value;
                this.RaisePropertyChanged("TotalRewardableAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalRewardableAmountSpecified {
            get {
                return this.totalRewardableAmountFieldSpecified;
            }
            set {
                this.totalRewardableAmountFieldSpecified = value;
                this.RaisePropertyChanged("TotalRewardableAmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public decimal VatAmount {
            get {
                return this.vatAmountField;
            }
            set {
                this.vatAmountField = value;
                this.RaisePropertyChanged("VatAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VatAmountSpecified {
            get {
                return this.vatAmountFieldSpecified;
            }
            set {
                this.vatAmountFieldSpecified = value;
                this.RaisePropertyChanged("VatAmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public double VATRate {
            get {
                return this.vATRateField;
            }
            set {
                this.vATRateField = value;
                this.RaisePropertyChanged("VATRate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VATRateSpecified {
            get {
                return this.vATRateFieldSpecified;
            }
            set {
                this.vATRateFieldSpecified = value;
                this.RaisePropertyChanged("VATRateSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.payback.net/lmsglobal/xsd/v1/types")]
    public partial class CollectEventType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PartnerContextType partnerField;
        
        private System.DateTime effectiveDateField;
        
        private string receiptNumberField;
        
        private string communicationChannelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PartnerContextType Partner {
            get {
                return this.partnerField;
            }
            set {
                this.partnerField = value;
                this.RaisePropertyChanged("Partner");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime EffectiveDate {
            get {
                return this.effectiveDateField;
            }
            set {
                this.effectiveDateField = value;
                this.RaisePropertyChanged("EffectiveDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ReceiptNumber {
            get {
                return this.receiptNumberField;
            }
            set {
                this.receiptNumberField = value;
                this.RaisePropertyChanged("ReceiptNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger", Order=3)]
        public string CommunicationChannel {
            get {
                return this.communicationChannelField;
            }
            set {
                this.communicationChannelField = value;
                this.RaisePropertyChanged("CommunicationChannel");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.payback.net/lmsglobal/xsd/v1/types")]
    public partial class PartnerContextType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string partnerShortNameField;
        
        private string businessUnitShortNameField;
        
        private string branchShortNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PartnerShortName {
            get {
                return this.partnerShortNameField;
            }
            set {
                this.partnerShortNameField = value;
                this.RaisePropertyChanged("PartnerShortName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string BusinessUnitShortName {
            get {
                return this.businessUnitShortNameField;
            }
            set {
                this.businessUnitShortNameField = value;
                this.RaisePropertyChanged("BusinessUnitShortName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string BranchShortName {
            get {
                return this.branchShortNameField;
            }
            set {
                this.branchShortNameField = value;
                this.RaisePropertyChanged("BranchShortName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.payback.net/lmsglobal/xsd/v1/types")]
    public partial class TextItemType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string textKeyField;
        
        private string textValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string TextKey {
            get {
                return this.textKeyField;
            }
            set {
                this.textKeyField = value;
                this.RaisePropertyChanged("TextKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TextValue {
            get {
                return this.textValueField;
            }
            set {
                this.textValueField = value;
                this.RaisePropertyChanged("TextValue");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.payback.net/lmsglobal/xsd/v1/types")]
    public partial class ValidityType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime validFromField;
        
        private System.DateTime validToField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime ValidFrom {
            get {
                return this.validFromField;
            }
            set {
                this.validFromField = value;
                this.RaisePropertyChanged("ValidFrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime ValidTo {
            get {
                return this.validToField;
            }
            set {
                this.validToField = value;
                this.RaisePropertyChanged("ValidTo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.payback.net/lmsglobal/xsd/v1/types")]
    public partial class CouponsOnReceiptType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string couponIDField;
        
        private ValidityType validityField;
        
        private TextItemType[] couponContentSetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CouponID {
            get {
                return this.couponIDField;
            }
            set {
                this.couponIDField = value;
                this.RaisePropertyChanged("CouponID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ValidityType Validity {
            get {
                return this.validityField;
            }
            set {
                this.validityField = value;
                this.RaisePropertyChanged("Validity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("TextItem", IsNullable=false)]
        public TextItemType[] CouponContentSet {
            get {
                return this.couponContentSetField;
            }
            set {
                this.couponContentSetField = value;
                this.RaisePropertyChanged("CouponContentSet");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.payback.net/lmsglobal/xsd/v1/types")]
    public partial class FaultDescriptorType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string messageField;
        
        private string requestIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string RequestID {
            get {
                return this.requestIDField;
            }
            set {
                this.requestIDField = value;
                this.RaisePropertyChanged("RequestID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.payback.net/lmsglobal/xsd/v1/types")]
    public partial class MessageResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FaultDescriptorType faultMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public FaultDescriptorType FaultMessage {
            get {
                return this.faultMessageField;
            }
            set {
                this.faultMessageField = value;
                this.RaisePropertyChanged("FaultMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.payback.net/lmsglobal/xsd/v1/types")]
    public partial class ConsumerAuthenticationType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string principalField;
        
        private string credentialField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Principal {
            get {
                return this.principalField;
            }
            set {
                this.principalField = value;
                this.RaisePropertyChanged("Principal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Credential {
            get {
                return this.credentialField;
            }
            set {
                this.credentialField = value;
                this.RaisePropertyChanged("Credential");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.payback.net/lmsglobal/xsd/v1/types")]
    public partial class ConsumerIdentificationType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ConsumerAuthenticationType consumerAuthenticationField;
        
        private VersionType versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ConsumerAuthenticationType ConsumerAuthentication {
            get {
                return this.consumerAuthenticationField;
            }
            set {
                this.consumerAuthenticationField = value;
                this.RaisePropertyChanged("ConsumerAuthentication");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public VersionType Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.payback.net/lmsglobal/xsd/v1/types")]
    public enum VersionType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.payback.net/lmsglobal/xsd/v1/types")]
    public partial class AuthorisedRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ConsumerIdentificationType consumerIdentificationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ConsumerIdentificationType ConsumerIdentification {
            get {
                return this.consumerIdentificationField;
            }
            set {
                this.consumerIdentificationField = value;
                this.RaisePropertyChanged("ConsumerIdentification");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.payback.net/lmsglobal/ws/v1/extint/types")]
    public partial class GetCouponsOnReceiptResponse : MessageResponse {
        
        private CouponsOnReceiptType[] couponListItemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CouponListItem", Order=0)]
        public CouponsOnReceiptType[] CouponListItem {
            get {
                return this.couponListItemField;
            }
            set {
                this.couponListItemField = value;
                this.RaisePropertyChanged("CouponListItem");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCouponsOnReceiptRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.payback.net/lmsglobal/ws/v1/extint/types", Order=0)]
        public WebPOS.WsAcumulation.GetCouponsOnReceiptRequest GetCouponsOnReceiptRequest;
        
        public GetCouponsOnReceiptRequest1() {
        }
        
        public GetCouponsOnReceiptRequest1(WebPOS.WsAcumulation.GetCouponsOnReceiptRequest GetCouponsOnReceiptRequest) {
            this.GetCouponsOnReceiptRequest = GetCouponsOnReceiptRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCouponsOnReceiptResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.payback.net/lmsglobal/ws/v1/extint/types", Order=0)]
        public WebPOS.WsAcumulation.GetCouponsOnReceiptResponse GetCouponsOnReceiptResponse;
        
        public GetCouponsOnReceiptResponse1() {
        }
        
        public GetCouponsOnReceiptResponse1(WebPOS.WsAcumulation.GetCouponsOnReceiptResponse GetCouponsOnReceiptResponse) {
            this.GetCouponsOnReceiptResponse = GetCouponsOnReceiptResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.payback.net/lmsglobal/ws/v1/extint/types")]
    public partial class ProcessPurchaseAndPromotionEventRequest : AuthorisedRequest {
        
        private MemberAliasIdentificationType authenticationField;
        
        private CollectEventType collectEventDataField;
        
        private int purchaseEventTypeField;
        
        private LegalUnitType rewardableLegalValueField;
        
        private LegalUnitType totalPurchaseLegalValueField;
        
        private LegalUnitType totalVatLegalValueField;
        
        private int paymentTypeField;
        
        private bool paymentTypeFieldSpecified;
        
        private string[] couponCodesField;
        
        private PurchaseItemDetails[] purchaseItemDetailsField;
        
        private TransactionDetails[] transactionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MemberAliasIdentificationType Authentication {
            get {
                return this.authenticationField;
            }
            set {
                this.authenticationField = value;
                this.RaisePropertyChanged("Authentication");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public CollectEventType CollectEventData {
            get {
                return this.collectEventDataField;
            }
            set {
                this.collectEventDataField = value;
                this.RaisePropertyChanged("CollectEventData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int PurchaseEventType {
            get {
                return this.purchaseEventTypeField;
            }
            set {
                this.purchaseEventTypeField = value;
                this.RaisePropertyChanged("PurchaseEventType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public LegalUnitType RewardableLegalValue {
            get {
                return this.rewardableLegalValueField;
            }
            set {
                this.rewardableLegalValueField = value;
                this.RaisePropertyChanged("RewardableLegalValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public LegalUnitType TotalPurchaseLegalValue {
            get {
                return this.totalPurchaseLegalValueField;
            }
            set {
                this.totalPurchaseLegalValueField = value;
                this.RaisePropertyChanged("TotalPurchaseLegalValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public LegalUnitType TotalVatLegalValue {
            get {
                return this.totalVatLegalValueField;
            }
            set {
                this.totalVatLegalValueField = value;
                this.RaisePropertyChanged("TotalVatLegalValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int PaymentType {
            get {
                return this.paymentTypeField;
            }
            set {
                this.paymentTypeField = value;
                this.RaisePropertyChanged("PaymentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PaymentTypeSpecified {
            get {
                return this.paymentTypeFieldSpecified;
            }
            set {
                this.paymentTypeFieldSpecified = value;
                this.RaisePropertyChanged("PaymentTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CouponCodes", Order=7)]
        public string[] CouponCodes {
            get {
                return this.couponCodesField;
            }
            set {
                this.couponCodesField = value;
                this.RaisePropertyChanged("CouponCodes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PurchaseItemDetails", Order=8)]
        public PurchaseItemDetails[] PurchaseItemDetails {
            get {
                return this.purchaseItemDetailsField;
            }
            set {
                this.purchaseItemDetailsField = value;
                this.RaisePropertyChanged("PurchaseItemDetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Transactions", Order=9)]
        public TransactionDetails[] Transactions {
            get {
                return this.transactionsField;
            }
            set {
                this.transactionsField = value;
                this.RaisePropertyChanged("Transactions");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.payback.net/lmsglobal/ws/v1/extint/types")]
    public partial class ProcessPurchaseAndPromotionEventResponse : MessageResponse {
        
        private AccountBalanceDetailType accountBalanceDetailsField;
        
        private TransactionDetails[] transactionsField;
        
        private CollectionInformationType collectionInformationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AccountBalanceDetailType AccountBalanceDetails {
            get {
                return this.accountBalanceDetailsField;
            }
            set {
                this.accountBalanceDetailsField = value;
                this.RaisePropertyChanged("AccountBalanceDetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Transactions", Order=1)]
        public TransactionDetails[] Transactions {
            get {
                return this.transactionsField;
            }
            set {
                this.transactionsField = value;
                this.RaisePropertyChanged("Transactions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public CollectionInformationType CollectionInformation {
            get {
                return this.collectionInformationField;
            }
            set {
                this.collectionInformationField = value;
                this.RaisePropertyChanged("CollectionInformation");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessPurchaseAndPromotionEventRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.payback.net/lmsglobal/ws/v1/extint/types", Order=0)]
        public WebPOS.WsAcumulation.ProcessPurchaseAndPromotionEventRequest ProcessPurchaseAndPromotionEventRequest;
        
        public ProcessPurchaseAndPromotionEventRequest1() {
        }
        
        public ProcessPurchaseAndPromotionEventRequest1(WebPOS.WsAcumulation.ProcessPurchaseAndPromotionEventRequest ProcessPurchaseAndPromotionEventRequest) {
            this.ProcessPurchaseAndPromotionEventRequest = ProcessPurchaseAndPromotionEventRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessPurchaseAndPromotionEventResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.payback.net/lmsglobal/ws/v1/extint/types", Order=0)]
        public WebPOS.WsAcumulation.ProcessPurchaseAndPromotionEventResponse ProcessPurchaseAndPromotionEventResponse;
        
        public ProcessPurchaseAndPromotionEventResponse1() {
        }
        
        public ProcessPurchaseAndPromotionEventResponse1(WebPOS.WsAcumulation.ProcessPurchaseAndPromotionEventResponse ProcessPurchaseAndPromotionEventResponse) {
            this.ProcessPurchaseAndPromotionEventResponse = ProcessPurchaseAndPromotionEventResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.payback.net/lmsglobal/ws/v1/extint/types")]
    public partial class RefundPurchaseEventRequest : AuthorisedRequest {
        
        private MemberAliasIdentificationType authenticationField;
        
        private CollectEventType collectEventDataField;
        
        private int purchaseEventTypeField;
        
        private string referenceReceiptNumberField;
        
        private LegalUnitType refundLegalValueField;
        
        private LegalUnitType refundVatLegalValueField;
        
        private PurchaseItemDetails[] refundItemDetailsField;
        
        private TransactionDetails[] transactionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MemberAliasIdentificationType Authentication {
            get {
                return this.authenticationField;
            }
            set {
                this.authenticationField = value;
                this.RaisePropertyChanged("Authentication");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public CollectEventType CollectEventData {
            get {
                return this.collectEventDataField;
            }
            set {
                this.collectEventDataField = value;
                this.RaisePropertyChanged("CollectEventData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int PurchaseEventType {
            get {
                return this.purchaseEventTypeField;
            }
            set {
                this.purchaseEventTypeField = value;
                this.RaisePropertyChanged("PurchaseEventType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ReferenceReceiptNumber {
            get {
                return this.referenceReceiptNumberField;
            }
            set {
                this.referenceReceiptNumberField = value;
                this.RaisePropertyChanged("ReferenceReceiptNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public LegalUnitType RefundLegalValue {
            get {
                return this.refundLegalValueField;
            }
            set {
                this.refundLegalValueField = value;
                this.RaisePropertyChanged("RefundLegalValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public LegalUnitType RefundVatLegalValue {
            get {
                return this.refundVatLegalValueField;
            }
            set {
                this.refundVatLegalValueField = value;
                this.RaisePropertyChanged("RefundVatLegalValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RefundItemDetails", Order=6)]
        public PurchaseItemDetails[] RefundItemDetails {
            get {
                return this.refundItemDetailsField;
            }
            set {
                this.refundItemDetailsField = value;
                this.RaisePropertyChanged("RefundItemDetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Transactions", Order=7)]
        public TransactionDetails[] Transactions {
            get {
                return this.transactionsField;
            }
            set {
                this.transactionsField = value;
                this.RaisePropertyChanged("Transactions");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.payback.net/lmsglobal/ws/v1/extint/types")]
    public partial class RefundPurchaseEventResponse : MessageResponse {
        
        private AccountBalanceDetailType accountBalanceDetailsField;
        
        private TransactionDetails[] transactionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AccountBalanceDetailType AccountBalanceDetails {
            get {
                return this.accountBalanceDetailsField;
            }
            set {
                this.accountBalanceDetailsField = value;
                this.RaisePropertyChanged("AccountBalanceDetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Transactions", Order=1)]
        public TransactionDetails[] Transactions {
            get {
                return this.transactionsField;
            }
            set {
                this.transactionsField = value;
                this.RaisePropertyChanged("Transactions");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RefundPurchaseEventRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.payback.net/lmsglobal/ws/v1/extint/types", Order=0)]
        public WebPOS.WsAcumulation.RefundPurchaseEventRequest RefundPurchaseEventRequest;
        
        public RefundPurchaseEventRequest1() {
        }
        
        public RefundPurchaseEventRequest1(WebPOS.WsAcumulation.RefundPurchaseEventRequest RefundPurchaseEventRequest) {
            this.RefundPurchaseEventRequest = RefundPurchaseEventRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RefundPurchaseEventResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.payback.net/lmsglobal/ws/v1/extint/types", Order=0)]
        public WebPOS.WsAcumulation.RefundPurchaseEventResponse RefundPurchaseEventResponse;
        
        public RefundPurchaseEventResponse1() {
        }
        
        public RefundPurchaseEventResponse1(WebPOS.WsAcumulation.RefundPurchaseEventResponse RefundPurchaseEventResponse) {
            this.RefundPurchaseEventResponse = RefundPurchaseEventResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.payback.net/lmsglobal/ws/v1/extint/types")]
    public partial class ReverseCollectEventRequest : AuthorisedRequest {
        
        private MemberAliasIdentificationType authenticationField;
        
        private CollectEventType collectEventDataField;
        
        private string referenceReceiptNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MemberAliasIdentificationType Authentication {
            get {
                return this.authenticationField;
            }
            set {
                this.authenticationField = value;
                this.RaisePropertyChanged("Authentication");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public CollectEventType CollectEventData {
            get {
                return this.collectEventDataField;
            }
            set {
                this.collectEventDataField = value;
                this.RaisePropertyChanged("CollectEventData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ReferenceReceiptNumber {
            get {
                return this.referenceReceiptNumberField;
            }
            set {
                this.referenceReceiptNumberField = value;
                this.RaisePropertyChanged("ReferenceReceiptNumber");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.payback.net/lmsglobal/ws/v1/extint/types")]
    public partial class ReverseCollectEventResponse : MessageResponse {
        
        private AccountBalanceDetailType accountBalanceDetailsField;
        
        private TransactionDetails[] transactionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AccountBalanceDetailType AccountBalanceDetails {
            get {
                return this.accountBalanceDetailsField;
            }
            set {
                this.accountBalanceDetailsField = value;
                this.RaisePropertyChanged("AccountBalanceDetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Transactions", Order=1)]
        public TransactionDetails[] Transactions {
            get {
                return this.transactionsField;
            }
            set {
                this.transactionsField = value;
                this.RaisePropertyChanged("Transactions");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReverseCollectEventRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.payback.net/lmsglobal/ws/v1/extint/types", Order=0)]
        public WebPOS.WsAcumulation.ReverseCollectEventRequest ReverseCollectEventRequest;
        
        public ReverseCollectEventRequest1() {
        }
        
        public ReverseCollectEventRequest1(WebPOS.WsAcumulation.ReverseCollectEventRequest ReverseCollectEventRequest) {
            this.ReverseCollectEventRequest = ReverseCollectEventRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReverseCollectEventResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.payback.net/lmsglobal/ws/v1/extint/types", Order=0)]
        public WebPOS.WsAcumulation.ReverseCollectEventResponse ReverseCollectEventResponse;
        
        public ReverseCollectEventResponse1() {
        }
        
        public ReverseCollectEventResponse1(WebPOS.WsAcumulation.ReverseCollectEventResponse ReverseCollectEventResponse) {
            this.ReverseCollectEventResponse = ReverseCollectEventResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ExtintPortTypeChannel : WebPOS.WsAcumulation.ExtintPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExtintPortTypeClient : System.ServiceModel.ClientBase<WebPOS.WsAcumulation.ExtintPortType>, WebPOS.WsAcumulation.ExtintPortType {
        
        public ExtintPortTypeClient() {
        }
        
        public ExtintPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExtintPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExtintPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExtintPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebPOS.WsAcumulation.GetCouponsOnReceiptResponse1 WebPOS.WsAcumulation.ExtintPortType.GetCouponsOnReceipt(WebPOS.WsAcumulation.GetCouponsOnReceiptRequest1 request) {
            return base.Channel.GetCouponsOnReceipt(request);
        }
        
        public WebPOS.WsAcumulation.GetCouponsOnReceiptResponse GetCouponsOnReceipt(WebPOS.WsAcumulation.GetCouponsOnReceiptRequest GetCouponsOnReceiptRequest) {
            WebPOS.WsAcumulation.GetCouponsOnReceiptRequest1 inValue = new WebPOS.WsAcumulation.GetCouponsOnReceiptRequest1();
            inValue.GetCouponsOnReceiptRequest = GetCouponsOnReceiptRequest;
            WebPOS.WsAcumulation.GetCouponsOnReceiptResponse1 retVal = ((WebPOS.WsAcumulation.ExtintPortType)(this)).GetCouponsOnReceipt(inValue);
            return retVal.GetCouponsOnReceiptResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebPOS.WsAcumulation.GetCouponsOnReceiptResponse1> WebPOS.WsAcumulation.ExtintPortType.GetCouponsOnReceiptAsync(WebPOS.WsAcumulation.GetCouponsOnReceiptRequest1 request) {
            return base.Channel.GetCouponsOnReceiptAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebPOS.WsAcumulation.GetCouponsOnReceiptResponse1> GetCouponsOnReceiptAsync(WebPOS.WsAcumulation.GetCouponsOnReceiptRequest GetCouponsOnReceiptRequest) {
            WebPOS.WsAcumulation.GetCouponsOnReceiptRequest1 inValue = new WebPOS.WsAcumulation.GetCouponsOnReceiptRequest1();
            inValue.GetCouponsOnReceiptRequest = GetCouponsOnReceiptRequest;
            return ((WebPOS.WsAcumulation.ExtintPortType)(this)).GetCouponsOnReceiptAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebPOS.WsAcumulation.ProcessPurchaseAndPromotionEventResponse1 WebPOS.WsAcumulation.ExtintPortType.ProcessPurchaseAndPromotionEvent(WebPOS.WsAcumulation.ProcessPurchaseAndPromotionEventRequest1 request) {
            return base.Channel.ProcessPurchaseAndPromotionEvent(request);
        }
        
        public WebPOS.WsAcumulation.ProcessPurchaseAndPromotionEventResponse ProcessPurchaseAndPromotionEvent(WebPOS.WsAcumulation.ProcessPurchaseAndPromotionEventRequest ProcessPurchaseAndPromotionEventRequest) {
            WebPOS.WsAcumulation.ProcessPurchaseAndPromotionEventRequest1 inValue = new WebPOS.WsAcumulation.ProcessPurchaseAndPromotionEventRequest1();
            inValue.ProcessPurchaseAndPromotionEventRequest = ProcessPurchaseAndPromotionEventRequest;
            WebPOS.WsAcumulation.ProcessPurchaseAndPromotionEventResponse1 retVal = ((WebPOS.WsAcumulation.ExtintPortType)(this)).ProcessPurchaseAndPromotionEvent(inValue);
            return retVal.ProcessPurchaseAndPromotionEventResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebPOS.WsAcumulation.ProcessPurchaseAndPromotionEventResponse1> WebPOS.WsAcumulation.ExtintPortType.ProcessPurchaseAndPromotionEventAsync(WebPOS.WsAcumulation.ProcessPurchaseAndPromotionEventRequest1 request) {
            return base.Channel.ProcessPurchaseAndPromotionEventAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebPOS.WsAcumulation.ProcessPurchaseAndPromotionEventResponse1> ProcessPurchaseAndPromotionEventAsync(WebPOS.WsAcumulation.ProcessPurchaseAndPromotionEventRequest ProcessPurchaseAndPromotionEventRequest) {
            WebPOS.WsAcumulation.ProcessPurchaseAndPromotionEventRequest1 inValue = new WebPOS.WsAcumulation.ProcessPurchaseAndPromotionEventRequest1();
            inValue.ProcessPurchaseAndPromotionEventRequest = ProcessPurchaseAndPromotionEventRequest;
            return ((WebPOS.WsAcumulation.ExtintPortType)(this)).ProcessPurchaseAndPromotionEventAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebPOS.WsAcumulation.RefundPurchaseEventResponse1 WebPOS.WsAcumulation.ExtintPortType.RefundPurchaseEvent(WebPOS.WsAcumulation.RefundPurchaseEventRequest1 request) {
            return base.Channel.RefundPurchaseEvent(request);
        }
        
        public WebPOS.WsAcumulation.RefundPurchaseEventResponse RefundPurchaseEvent(WebPOS.WsAcumulation.RefundPurchaseEventRequest RefundPurchaseEventRequest) {
            WebPOS.WsAcumulation.RefundPurchaseEventRequest1 inValue = new WebPOS.WsAcumulation.RefundPurchaseEventRequest1();
            inValue.RefundPurchaseEventRequest = RefundPurchaseEventRequest;
            WebPOS.WsAcumulation.RefundPurchaseEventResponse1 retVal = ((WebPOS.WsAcumulation.ExtintPortType)(this)).RefundPurchaseEvent(inValue);
            return retVal.RefundPurchaseEventResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebPOS.WsAcumulation.RefundPurchaseEventResponse1> WebPOS.WsAcumulation.ExtintPortType.RefundPurchaseEventAsync(WebPOS.WsAcumulation.RefundPurchaseEventRequest1 request) {
            return base.Channel.RefundPurchaseEventAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebPOS.WsAcumulation.RefundPurchaseEventResponse1> RefundPurchaseEventAsync(WebPOS.WsAcumulation.RefundPurchaseEventRequest RefundPurchaseEventRequest) {
            WebPOS.WsAcumulation.RefundPurchaseEventRequest1 inValue = new WebPOS.WsAcumulation.RefundPurchaseEventRequest1();
            inValue.RefundPurchaseEventRequest = RefundPurchaseEventRequest;
            return ((WebPOS.WsAcumulation.ExtintPortType)(this)).RefundPurchaseEventAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebPOS.WsAcumulation.ReverseCollectEventResponse1 WebPOS.WsAcumulation.ExtintPortType.ReverseCollectEvent(WebPOS.WsAcumulation.ReverseCollectEventRequest1 request) {
            return base.Channel.ReverseCollectEvent(request);
        }
        
        public WebPOS.WsAcumulation.ReverseCollectEventResponse ReverseCollectEvent(WebPOS.WsAcumulation.ReverseCollectEventRequest ReverseCollectEventRequest) {
            WebPOS.WsAcumulation.ReverseCollectEventRequest1 inValue = new WebPOS.WsAcumulation.ReverseCollectEventRequest1();
            inValue.ReverseCollectEventRequest = ReverseCollectEventRequest;
            WebPOS.WsAcumulation.ReverseCollectEventResponse1 retVal = ((WebPOS.WsAcumulation.ExtintPortType)(this)).ReverseCollectEvent(inValue);
            return retVal.ReverseCollectEventResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebPOS.WsAcumulation.ReverseCollectEventResponse1> WebPOS.WsAcumulation.ExtintPortType.ReverseCollectEventAsync(WebPOS.WsAcumulation.ReverseCollectEventRequest1 request) {
            return base.Channel.ReverseCollectEventAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebPOS.WsAcumulation.ReverseCollectEventResponse1> ReverseCollectEventAsync(WebPOS.WsAcumulation.ReverseCollectEventRequest ReverseCollectEventRequest) {
            WebPOS.WsAcumulation.ReverseCollectEventRequest1 inValue = new WebPOS.WsAcumulation.ReverseCollectEventRequest1();
            inValue.ReverseCollectEventRequest = ReverseCollectEventRequest;
            return ((WebPOS.WsAcumulation.ExtintPortType)(this)).ReverseCollectEventAsync(inValue);
        }
    }
}
